"""
Analyzer: Ground-truth backport comparison (syzbot fixes vs. all kernel fixes).

Uses the cherry-pick mapping extracted from linux-stable.git to compare
backport patterns of syzbot-found bug fixes against the broader kernel.

Requires: dataset/data/processed/cherrypick_map.json
  (generated by: python -m dataset.scraper.stable_cherrypick)
"""

import json
import re
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from statistics import median
from typing import Any, Optional

from ..loader import BugEntry
from .base import BaseAnalyzer, AnalysisResult

CHERRYPICK_MAP_PATH = (
    Path(__file__).resolve().parent.parent.parent
    / "dataset" / "data" / "processed" / "cherrypick_map.json"
)


def _parse_iso_date(s: str) -> Optional[datetime]:
    """Parse ISO 8601 date string."""
    if not s:
        return None
    try:
        # Handle Z suffix and timezone offsets
        s = s.replace("Z", "+00:00")
        return datetime.fromisoformat(s)
    except ValueError:
        return None


def _branch_to_version(branch: str) -> str:
    """Extract version from branch name, e.g. 'linux-5.4.y' -> '5.4'."""
    m = re.search(r'(\d+\.\d+)', branch)
    return m.group(1) if m else branch


def _get_subsystem(bug: BugEntry) -> str:
    """Extract top-level subsystem from fix commit paths."""
    for fc in bug.fix_commits:
        if not fc.patch_diff:
            continue
        files = re.findall(r'diff --git a/(\S+)', fc.patch_diff)
        if files:
            return files[0].split('/')[0]
    return "unknown"


class BackportComparisonAnalyzer(BaseAnalyzer):
    """Compare syzbot-fix backport patterns against all-kernel baseline."""

    @property
    def name(self) -> str:
        return "Backport Ground Truth Comparison"

    def analyze(self, bugs: list[BugEntry]) -> AnalysisResult:
        # Load cherry-pick mapping
        if not CHERRYPICK_MAP_PATH.exists():
            return AnalysisResult(
                name=self.name,
                summary={
                    "error": "cherrypick_map.json not found",
                    "hint": "Run: python -m dataset.scraper.stable_cherrypick",
                },
            )

        with open(CHERRYPICK_MAP_PATH) as f:
            mapping = json.load(f)

        u2b = mapping["upstream_to_backports"]  # upstream_hash -> [backports]
        upstream_dates = mapping.get("upstream_dates", {})
        meta = mapping["metadata"]
        all_branches = set()
        for backports in u2b.values():
            for bp in backports:
                all_branches.add(bp["branch"])
        all_branches = sorted(all_branches)

        # ── All-fix baseline stats ───────────────────────────────────
        all_total = len(u2b)
        all_branch_counts: Counter = Counter()
        all_coverage: list[int] = []
        all_lag_days: list[float] = []
        all_per_branch_lag: dict[str, list[float]] = defaultdict(list)

        for upstream_hash, backports in u2b.items():
            branches_hit = set(bp["branch"] for bp in backports)
            all_coverage.append(len(branches_hit))
            for bp in backports:
                all_branch_counts[bp["branch"]] += 1

            # Compute lag if upstream date available
            up_date = _parse_iso_date(upstream_dates.get(upstream_hash, ""))
            if up_date:
                for bp in backports:
                    bp_date = _parse_iso_date(bp["date"])
                    if bp_date:
                        lag = (bp_date.replace(tzinfo=None) - up_date.replace(tzinfo=None)).total_seconds() / 86400
                        if 0 <= lag <= 365:
                            all_lag_days.append(lag)
                            all_per_branch_lag[bp["branch"]].append(lag)

        # ── Syzbot fix stats ─────────────────────────────────────────
        syz_total = 0
        syz_found = 0
        syz_branch_counts: Counter = Counter()
        syz_coverage: list[int] = []
        syz_lag_days: list[float] = []
        syz_per_branch_lag: dict[str, list[float]] = defaultdict(list)
        syz_missing: list[dict] = []
        syz_subsystem_total: Counter = Counter()
        syz_subsystem_backported: Counter = Counter()

        per_bug_details: list[dict[str, Any]] = []

        for bug in bugs:
            for fc in bug.fix_commits:
                if not fc.hash:
                    continue
                syz_total += 1
                subsystem = _get_subsystem(bug)
                syz_subsystem_total[subsystem] += 1

                backports = u2b.get(fc.hash, [])
                if backports:
                    syz_found += 1
                    branches_hit = set(bp["branch"] for bp in backports)
                    syz_coverage.append(len(branches_hit))
                    syz_subsystem_backported[subsystem] += 1

                    for bp in backports:
                        syz_branch_counts[bp["branch"]] += 1

                    # Lag — prefer syzbot's commit date (from torvalds/linux)
                    up_date_str = fc.date or upstream_dates.get(fc.hash, "")
                    up_date = _parse_iso_date(up_date_str)
                    if up_date:
                        for bp in backports:
                            bp_date = _parse_iso_date(bp["date"])
                            if bp_date:
                                lag = (bp_date.replace(tzinfo=None) - up_date.replace(tzinfo=None)).total_seconds() / 86400
                                if 0 <= lag <= 365:
                                    syz_lag_days.append(lag)
                                    syz_per_branch_lag[bp["branch"]].append(lag)

                    per_bug_details.append({
                        "bug_id": bug.bug_id,
                        "title": bug.title,
                        "upstream_hash": fc.hash[:12],
                        "subsystem": subsystem,
                        "branches_backported": sorted(_branch_to_version(b) for b in branches_hit),
                        "num_branches": len(branches_hit),
                    })
                else:
                    syz_coverage.append(0)
                    syz_missing.append({
                        "bug_id": bug.bug_id,
                        "title": bug.title[:60],
                        "upstream_hash": fc.hash[:12],
                        "subsystem": subsystem,
                    })

        # ── Summary ──────────────────────────────────────────────────
        def _safe_median(lst):
            return round(median(lst), 1) if lst else None

        def _safe_mean(lst):
            return round(sum(lst) / len(lst), 2) if lst else None

        syz_backport_rate = syz_found / max(syz_total, 1) * 100
        # All-fix "backport rate" is 100% by construction (u2b only has
        # commits that WERE cherry-picked). We need total upstream commits
        # to compute a real rate. Use metadata if available.
        # For now, report counts and coverage depth.

        # Filter lag to only positive values (0.0 means same-day which is
        # unreliable for the all-kernel baseline since upstream dates come
        # from the stable repo's master branch, not torvalds/linux)
        syz_lag_positive = [d for d in syz_lag_days if d > 0.5]
        all_lag_positive = [d for d in all_lag_days if d > 0.5]

        summary: dict[str, Any] = {
            "Cherry-pick map": f"{meta['total_cherrypicks']} picks across {len(all_branches)} branches",
            "Unique upstream commits (all)": all_total,
            "Syzbot fix commits checked": syz_total,
            "Syzbot fixes found in stable": f"{syz_found} ({syz_backport_rate:.1f}%)",
            "Syzbot fixes NOT in stable": syz_total - syz_found,
            "Avg branches (syzbot backported)": _safe_mean([c for c in syz_coverage if c > 0]),
            "Avg branches (all backported)": _safe_mean(all_coverage),
            "Median lag days (syzbot, >0.5d)": _safe_median(syz_lag_positive),
            "Median lag days (all, >0.5d)": _safe_median(all_lag_positive),
        }

        # ── Tables ───────────────────────────────────────────────────

        # 1. Backport rate comparison
        rate_table = [
            {
                "metric": "Commits examined",
                "syzbot": syz_total,
                "all_kernel": all_total,
            },
            {
                "metric": "Found in stable trees",
                "syzbot": f"{syz_found} ({syz_backport_rate:.1f}%)",
                "all_kernel": f"{all_total} (baseline)",
            },
            {
                "metric": "Avg branches (backported only)",
                "syzbot": _safe_mean([c for c in syz_coverage if c > 0]),
                "all_kernel": _safe_mean(all_coverage),
            },
            {
                "metric": "Median backport lag (days, >0.5d)",
                "syzbot": _safe_median(syz_lag_positive),
                "all_kernel": _safe_median(all_lag_positive),
            },
        ]

        # 2. Per-branch rates
        branch_table = []
        for branch in sorted(all_branches, key=lambda b: _branch_to_version(b)):
            ver = _branch_to_version(branch)
            all_count = all_branch_counts.get(branch, 0)
            syz_count = syz_branch_counts.get(branch, 0)
            syz_rate = f"{syz_count / max(syz_found, 1) * 100:.1f}%" if syz_found else "N/A"
            branch_table.append({
                "branch": ver,
                "all_kernel_picks": all_count,
                "syzbot_picks": syz_count,
                "syzbot_pct_of_backported": syz_rate,
            })

        # 3. Lag comparison per branch (top branches only)
        lag_table = []
        for branch in sorted(all_branches, key=lambda b: _branch_to_version(b)):
            ver = _branch_to_version(branch)
            a_lags = all_per_branch_lag.get(branch, [])
            s_lags = syz_per_branch_lag.get(branch, [])
            if not a_lags:
                continue
            lag_table.append({
                "branch": ver,
                "median_lag_all": _safe_median(a_lags),
                "median_lag_syzbot": _safe_median(s_lags),
                "count_all": len(a_lags),
                "count_syzbot": len(s_lags),
            })

        # 4. Coverage tiers comparison
        def _tier(n):
            if n == 0:
                return "0 (not backported)"
            elif n == 1:
                return "1 branch"
            elif n <= 3:
                return "2-3 branches"
            elif n <= 5:
                return "4-5 branches"
            else:
                return "6+ branches"

        tier_order = ["0 (not backported)", "1 branch", "2-3 branches",
                      "4-5 branches", "6+ branches"]
        syz_tiers: Counter = Counter(_tier(n) for n in syz_coverage)
        all_tiers: Counter = Counter(_tier(n) for n in all_coverage)

        coverage_table = []
        for tier in tier_order:
            s_count = syz_tiers.get(tier, 0)
            a_count = all_tiers.get(tier, 0)
            coverage_table.append({
                "tier": tier,
                "syzbot_count": s_count,
                "syzbot_pct": f"{s_count / max(syz_total, 1) * 100:.1f}%",
                "all_count": a_count,
                "all_pct": f"{a_count / max(all_total, 1) * 100:.1f}%",
            })

        # 5. Subsystem comparison (top 15)
        subsystem_table = []
        for sub in sorted(syz_subsystem_total, key=lambda s: -syz_subsystem_total[s]):
            t = syz_subsystem_total[sub]
            if t < 5:
                continue
            b = syz_subsystem_backported.get(sub, 0)
            subsystem_table.append({
                "subsystem": sub,
                "syzbot_total": t,
                "syzbot_backported": b,
                "syzbot_rate": f"{b / t * 100:.1f}%",
            })
        subsystem_table = subsystem_table[:15]

        # 6. Syzbot fixes missing from stable (top 30)
        missing_table = syz_missing[:30]

        return AnalysisResult(
            name=self.name,
            summary=summary,
            details=per_bug_details[:100],
            tables={
                "backport_rate_comparison": rate_table,
                "per_branch_rates": branch_table,
                "lag_comparison": lag_table,
                "coverage_tiers_comparison": coverage_table,
                "subsystem_comparison": subsystem_table,
                "syzbot_missing_backports": missing_table,
            },
        )
